### ISSUE TITLE
Unable to fetch private repositories via grimoirelab/full image.

### ISSUE THREAD

**Issue by asharabu** [chaoss/grimoirelab#205]
Hi,

I have deployed a grimoirelab using docker image "grimoirelab/full".
I have generated personal access token with full permission and given it on credentials.cfg to mount override.cfg. 
Removed all the projects from projects.json and file and added one public and private repositories link on it. The public repo details is showing on kibana but the private repo is not fetching in to the directory on the container /home/grimoirelab/.perceval/repositories/https:/github.com/asharabu 

Please see the below docker error logs,
-----------
Loading unique identities...
2/2 unique identities loaded
Collection for git: starting...
2019-08-20 10:17:44,625 - grimoire_elk.elk - ERROR - Error feeding ocean from git (https://github.com/asharabu/Testgit123): git command - Cloning into bare repository '/home/grimoirelab/.perceval/repositories/https://github.com/asharabu/Testgit123-git'...
fatal: could not read Username for 'https://github.com': No such device or address
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 229, in feed_backend
    ocean_backend.feed(**params)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 229, in feed
    self.feed_items(items)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 245, in feed_items
    for item in items:
  File "/usr/local/lib/python3.5/dist-packages/perceval/backend.py", line 162, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 155, in fetch_items
    latest_items, no_update)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 268, in __fetch_from_repo
    repo = self.__create_git_repository()
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 319, in __create_git_repository
    repo = GitRepository.clone(self.uri, self.gitpath)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 827, in clone
    cls._exec(cmd, env=env)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 1332, in _exec
    raise RepositoryError(cause=cause)
perceval.errors.RepositoryError: git command - Cloning into bare repository '/home/grimoirelab/.perceval/repositories/https://github.com/asharabu/Testgit123-git'...
fatal: could not read Username for 'https://github.com': No such device or address

----------------------
Please guide me what is making the issue..

**Comment by valeriocos** [comment]
Hi @asharabu, sorry for the late reply. I'm looking into it.

**Comment by valeriocos** [comment]
The analysis of private repos on GitHub is not fully supported. A workaround is to include the credentials in the projects.json as follows:
```
"git": [
            "https://<username-github>:<api-token>@github.com/asharabu/Testgit123"
        ],
```

Please let me know if this solves your issue, thanks

**Comment by asharabu** [comment]
Hi,
Thanks for your update.
It is not working. It seems there should change on api related codes.  Please check and let me know.

**Comment by valeriocos** [comment]
Can you share your dashboard.cfg and projects.json, please?

**Comment by asharabu** [comment]
/$ cat dashboard.cfg
# Mordred configuration file (Dashboard)
# Parameters related to the dashboard and how it is produced
# This is usually updated by the person maintaining the dashboard
#
# List: [val1, val2 ...]
# Int: int_value
# Int as string: "Int"
# List as string: "[val1, val2 ...]"
# String: string_value
# None: None, none
# Boolean: true, True, False, false

[general]
# Update incrementally, forever
update = true
# Don't start a new update earlier than (since last update, seconds)
min_update_delay = 300
# Produce debugging data for the logs
debug = true

[es_enrichment]
# Refresh identities and projects for all items after enrichment
autorefresh = true

[sortinghat]
# Run affilation
affiliate = True
# How to match to unify
matching = [email]
# How long to sleep before running again, for identities tasks
sleep_for = 100

[panels]
# Dashboard: default time frame
kibiter_time_from = "now-1y"
# Dashboard: default index pattern
kibiter_default_index = "git"
# GitHub repos panels
github-repos = true

[phases]
collection = true
identities = true
enrichment = true
panels = true

[git]
# Names for raw and enriched indexes
raw_index = git_grimoirelab-raw
enriched_index = git_grimoirelab
studies = [enrich_demography:git, enrich_areas_of_code:git, enrich_onion:git]

[github]
# Names for raw and enriched indexes
raw_index = github_grimoirelab-raw
enriched_index = github_grimoirelab
# Sleep it GitHub API rate is exhausted, waited until it is recovered
sleep-for-rate = true

[pipermail]
# Names for raw and enriched indexes
raw_index = mail_grimoirelab-raw
enriched_index = mail_grimoirelab

# Studies

[enrich_demography:git]
#no_incremental = true   # default: false

[enrich_areas_of_code:git]
in_index = git_grimoirelab-raw
out_index = git_aoc_grimoirelab-enriched
#sort_on_field = metadata__timestamp
#no_incremental = false

[enrich_onion:git]
in_index = git_grimoirelab
out_index = git_onion_grimoirelab-enriched
#data_source = git
#contribs_field = hash
#timeframe_field = grimoire_creation_date
#sort_on_field = metadata__timestamp
#no_incremental = false
=============================
projects.json

{
    "TestAsharTest": {
        "git": [
            "https://asharabu:<key>@github.com/asharabu/Testgit123",
            "https://github.com/asharabu/First-repo",
            "https://asharabu-github:<key>@github.com/asharabu/ttt.git"
        ],
        "github": [
            "https://asharabu:<key>@github.com/asharabu/Testgit123",
            "https://github.com/asharabu/First-repo",
            "https://asharabu:<key>@github.com/asharabu/ttt.git"
        ]
    }
}
============

**Comment by valeriocos** [comment]
You don't need to pass the username and token to GitHub repos, since the token you set in `credentials.cfg` should have the right scope to access your GitHub data (e.g., issue, issue comments, etc.).

Try with the projects.json below.
```
{
"TestAsharTest": {
"git": [
   "https://asharabu:key@github.com/asharabu/Testgit123",
   "https://github.com/asharabu/First-repo",
   "https://asharabu:key@github.com/asharabu/ttt.git"
],
"github": [
   "https:/github.com/asharabu/Testgit123",
   "https://github.com/asharabu/First-repo",
   "https://github.com/asharabu/ttt.git"
]
}
}
```

Note that you can try to get access to your private Git repos via ssh (instead of passing the username and password on the projects.json), please check these links:
- https://stackoverflow.com/questions/2505096/cloning-a-private-github-repo
- https://github.community/t5/How-to-use-Git-and-GitHub/Clone-private-repo/td-p/12616

Hope it helps

**Comment by asharabu** [comment]
Hi,

Direct cloning is working in the container using the username and key OR ssh key. But the cloning is still not possible using projects.json.

I tried as you suggested on projects.json but still getting the below error,

-----------
2019-08-21 10:09:47,789 - grimoire_elk.elk - ERROR - Error feeding ocean from github (https://github.com/asharabu/ttt.git): 404 Client Error: Not Found for url: https://api.github.com/repos/asharabu/ttt.git/issues?sort=updated&state=all&since=1970-01-01T00%3A00%3A00%2B00%3A00&per_page=100&direction=asc
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 229, in feed_backend
    ocean_backend.feed(**params)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 229, in feed
    self.feed_items(items)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 245, in feed_items
    for item in items:
  File "/usr/local/lib/python3.5/dist-packages/perceval/backend.py", line 162, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 244, in __fetch_issues
    for raw_issues in issues_groups:
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 790, in fetch_items
    response = self.fetch(url_next, payload=payload)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 772, in fetch
    response = super().fetch(url, payload, headers, method, stream, verify)
  File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 132, in fetch
    response = self._fetch_from_remote(url, payload, headers, method, stream, verify)
  File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 173, in _fetch_from_remote
    raise e
  File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 168, in _fetch_from_remote
    response.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.github.com/repos/asharabu/ttt.git/issues?sort=updated&state=all&since=1970-01-01T00%3A00%3A00%2B00%3A00&per_page=100&direction=asc
Collection for github: finished after 00:00:11 hours

**Comment by valeriocos** [comment]
Hi @asharabu 
The error is now different from the one you reported originaly. Git works fine, the problem is with fetching GitHub data.
Is it possible that the credentials.cfg is not properly configured? The other option could be that the token doesn't have permission to access that repo.

In order to discard the second option, would you mind execute perceval from command line:
```
perceval github asharabu ttt --category issue -t <your-tken> --sleep-for-rate
```

**Comment by valeriocos** [comment]
any news on this issue @asharabu ?

**Comment by asharabu** [comment]
Hi,

The issue not yet solved. The above command returns the below output,

---

[2019-08-22 08:49:53,967] - Sir Perceval is on his quest.
[2019-08-22 08:49:54,996] - Sir Perceval completed his quest.

---

Also please see the credentials.cfg file,
  
----

 [github]
 api-token = key

---

**Comment by valeriocos** [comment]
> [2019-08-22 08:49:53,967] - Sir Perceval is on his quest.
> [2019-08-22 08:49:54,996] - Sir Perceval completed his quest.

This means that the token has the right permissions to access your private repo. 
The problem should be in the configuration. Your `credentials.cfg` looks OK, maybe the `credentials.cfg` is not correctly set with `$(pwd)/credentials.cfg:/override.cfg` (see full command below). Do you have other `credentials.cfg` files?

```
$ docker run -p 127.0.0.1:5601:5601 -v $(pwd)/credentials.cfg:/override.cfg -t grimoirelab/full
```

**Comment by asharabu** [comment]
Hi,

I have already verified the file credentials.cfg is correctly mounting to inside the container as the name override.cfg on the location root (/). But the issue still persists.  I suspect that the issue on the GitHub API calls on Grimorielab code.

**Comment by valeriocos** [comment]
thank you for the info. I'll check on some private repos and get back to you.

**Comment by valeriocos** [comment]
Hi @asharabu,

I don't see any issue when fetching github private repos. These are the steps I followed and the output of the container:
- create dir `/tmp/test-full`

- create the `credentials.cfg`
```
slimbook@slimbook-KATANA:/tmp/test-full$ cat credentials.cfg 
[github]
api-token = 747...
```

- create the `projects.json`
```
slimbook@slimbook-KATANA:/tmp/test-full$ cat projects.json 
  
{
    "grimoire": {
        "git": [
            "https://github.com/chaoss/grimoirelab-toolkit"
        ],
        "github": [
            "https://github.com/Bitergia/<private-repo>"
        ]
    }
}
```

- execute the following command :
```
/tmp/test-full$ docker run -p 127.0.0.1:5601:5601 -v $(pwd)/credentials.cfg:/override.cfg -v $(pwd)/projects.json:/projects.json -t grimoirelab/full
```

- output
```
slimbook@slimbook-KATANA:/tmp/test-full$ docker run -p 127.0.0.1:5601:5601 -v $(pwd)/credentials.cfg:/override.cfg -v $(pwd)/projects.json:/projects.json -t grimoirelab/full
Starting container: 0926b08da55a
Starting Elasticsearch
[ ok ] Starting Elasticsearch Server:.
Waiting for Elasticsearch to start...
tcp        0      0 0.0.0.0:9200            0.0.0.0:*               LISTEN      -                   
Elasticsearch started
Starting MariaDB
[ ok ] Starting MariaDB database server: mysqld.
Waiting for MariaDB to start...
tcp6       0      0 :::3306                 :::*                    LISTEN      -                   
MariaDB started
Starting Kibiter
Waiting for Kibiter to start...
..Kibiter started
Starting SirMordred to build a GrimoireLab dashboard
This will usually take a while...
Collection for github: starting...
Collection for git: starting...
Loading blacklist...
0/0 blacklist entries loaded
Loading unique identities...
Collection for github: finished after 00:00:03 hours
Collection for git: finished after 00:00:04 hours
53/53 unique identities loaded
Executing for git the studies ['enrich_demography:git', 'enrich_areas_of_code:git', 'enrich_onion:git']
Loading blacklist...
0/0 blacklist entries loaded
Loading unique identities...
53/53 unique identities loaded
Loading blacklist...
0/0 blacklist entries loaded
```

**Comment by asharabu** [comment]
Hi,

I can see that you have given public repo under git.

 slimbook@slimbook-KATANA:/tmp/test-full$ cat projects.json 

 
{
    "grimoire": {
        **"git": [
            "https://github.com/chaoss/grimoirelab-toolkit"**
        ],
        "github": [
            "https://github.com/Bitergia/\<private-repo\>"
        ]
    }
}

Please use private repo instead of public on git and see.

**Comment by valeriocos** [comment]
I understood that the error with git was solved using the urls https://user:key@github.com... since the error you posted at https://github.com/chaoss/grimoirelab/issues/205#issuecomment-523393506 was just about github. 
I changed the projects.json, followed the steps at https://github.com/chaoss/grimoirelab/issues/205#issuecomment-524689912 and no error was thrown (see details below).

Note that repos in the github section shouldn't end with `.git` as visible within the logs posted at https://github.com/chaoss/grimoirelab/issues/205#issuecomment-523393506

**projects.json**
```
tmp/test-full$ cat projects.json 
{
    "grimoire": {
        "git": [
            "https://valeriocos:74....@github.com/Bitergia/<private-repo>"
        ],
        "github": [
            "https://github.com/Bitergia/<private-repo>"
        ]
    }
}

```

**logs**
```
tmp/test-full$ docker run -p 127.0.0.1:5601:5601 -v $(pwd)/credentials.cfg:/override.cfg -v $(pwd)/projects.json:/projects.json -t grimoirelab/full
Starting container: 70c8eb228ae9
Starting Elasticsearch
[ ok ] Starting Elasticsearch Server:.
Waiting for Elasticsearch to start...
tcp        0      0 0.0.0.0:9200            0.0.0.0:*               LISTEN      -                   
Elasticsearch started
Starting MariaDB
[ ok ] Starting MariaDB database server: mysqld ..
Waiting for MariaDB to start...
tcp6       0      0 :::3306                 :::*                    LISTEN      -                   
MariaDB started
Starting Kibiter
Waiting for Kibiter to start...
...Kibiter started
Starting SirMordred to build a GrimoireLab dashboard
This will usually take a while...
Collection for github: starting...
Collection for git: starting...
Loading blacklist...
0/0 blacklist entries loaded
Loading unique identities...
Collection for github: finished after 00:00:02 hours
Collection for git: finished after 00:00:04 hours
53/53 unique identities loaded
Executing for git the studies ['enrich_demography:git', 'enrich_areas_of_code:git', 'enrich_onion:git']
Loading blacklist...
0/0 blacklist entries loaded
Loading unique identities...
53/53 unique identities loaded
Loading blacklist...
0/0 blacklist entries loaded
Loading unique identities...
53/53 unique identities
```

**Comment by valeriocos** [comment]
plese, can you check on your side @asharabu ?

**Comment by valeriocos** [comment]
I didn't detect any issue @asharabu , let's close this issue. Feel free to reopen it if needed, Thanks

**Comment by asharabu** [comment]
Hi,

Thanks. It was working and displaying the output when we give only git and github section on projects.json.

When adding the github:repo for private repo, it is still showing the error and the repository is not showing under tab "GitHub Repositories" on kibana dashboard. Please note that commit message counts are showing for the private repo on kibana dashboard under Overview.

Please see the ebtries which I gave on projects.json

    "Ashar-private": {
        "git": [
            "https://asharabu:<key>@github.com/asharabu/Testgit123"
        ],
        "github": [
            "https://github.com/asharabu/Testgit123"
        ],
        **"github:repo": [
            "https://asharabu:<key>@github.com/asharabu/Testgit123"**
        ]
    }

The error message is getting,

2019-08-27 10:15:08,298 - grimoire_elk.elk - ERROR - Error feeding ocean from github (https://github.com/asharabu/Testgit123): 404 Client Error: Not Found for url: https://api.github.com/repos/asharabu/Testgit123
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 229, in feed_backend
    ocean_backend.feed(**params)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 229, in feed
    self.feed_items(items)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 245, in feed_items
    for item in items:
  File "/usr/local/lib/python3.5/dist-packages/perceval/backend.py", line 162, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 305, in __fetch_repo_info
    raw_repo = self.client.repo()
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 663, in repo
    r = self.fetch(path)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 772, in fetch
    response = super().fetch(url, payload, headers, method, stream, verify)
  File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 132, in fetch
    response = self._fetch_from_remote(url, payload, headers, method, stream, verify)
  File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 173, in _fetch_from_remote
    raise e
  File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 168, in _fetch_from_remote
    response.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.github.com/repos/asharabu/Testgit123
Collection for github:repo: finished after 00:00:04 hours

**Comment by marcofranssen** [comment]
I'm facing exactly the same issue. Seems all repositories with an internal/private can't be accessed, with exactly the same error as discussed in this issue.

**Comment by valeriocos** [comment]
Hi @marcofranssen ,

Before reopening this issue, can you please provide your projects.json? This issue should be solved with https://github.com/chaoss/grimoirelab/issues/205#issuecomment-524746746

Thanks

**Comment by marcofranssen** [comment]
I figured it out. It seems all non public repositories do need the `user:token` name in the url in order to work properly. For public repos this isn't required. Although it is still a bit weird as the token is also already defined in credentials.cfg

**Comment by valeriocos** [comment]
Yes, all non public >Git< repository need user:token.

> Although it is still a bit weird as the token is also already defined in credentials.cfg

The token is used to access the GitHub API (to fetch issues and pull requests). Git commits are collected by (i) cloning the repo locally and (ii) inspect the log history, thus although the token is the same, it is passed in a different way (together with the GitHub username).

Please consider to open an issue if you want to propose a feature request. You can also improve the how to section at https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md#how-to-

Thanks

**Comment by ZsoltPath** [comment]
There seem to a be another issue with this approach.
When I click on the Discover tab, I can see my token in every entry.
<img width="649" alt="Annotation 2020-06-23 103848" src="https://user-images.githubusercontent.com/60187881/85388549-22859100-b53e-11ea-8485-b247600ce2c6.png">

Would it be possible to use SSH connection and private key authentication for private repos?

**Comment by valeriocos** [comment]
Hi @ZsoltPath , this is fixed since the release 0.2.41 (but the image grimoirelab/full isn't up-to-date). If you use the docker-compose solution, it should work.

> Would it be possible to use SSH connection and private key authentication for private repos?

It should be possible, please have a look at this comment https://github.com/chaoss/grimoirelab/issues/205#issuecomment-523358197 and the one below

**Comment by marcofranssen** [comment]
@valeriocos what about the grimoirelab/installed version?

In some other tickets it seems also some other issues have not yet reached the Docker containers.

When you are referring to the `docker-compose` solution, which specific one do you mean by that. I'm using a docker-compose setup in our case, but do notice most of these issues are still existent there.
